version: 2
updates:
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Only open PRs for security vulnerabilities, to minimize noise/breakages
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
